Refactor SETTINGS_SaveChannel to use union as buffer
The current code produces and error when compiled with strict aliasing
rules and std=c2x (-Werror=strict-aliasing -std=c2x):

settings.c:614:44: error: dereferencing type-punned pointer will break strict-aliasing rules
((uint32_t *)State)[0] = pVFO->freq_config_RX.Frequency;

State has been declared as a union to fix the aforementioned issue and
to ease its usage as uint8_t and uint32_t buffer.